export const data = [
    {
        ID: 4512,
        "Yayın id": "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
    {
        ID: 4512,
        isim: "Bir Kuş Olsam",
        yayinEvi: "Leylak Yayınevi",
        yazar: "Can Okulmuş",
        sayfa: "369",
    },
]